/**
 * Curated Google Fonts for event title picker (no other imports — avoids Turbopack init-order issues).
 */

export type GoogleFontEntry = { family: string; group: "Serif" | "Sans" | "Display" | "Script" }

export const GOOGLE_TITLE_FONTS: GoogleFontEntry[] = [
  { family: "Playfair Display", group: "Serif" },
  { family: "Merriweather", group: "Serif" },
  { family: "Lora", group: "Serif" },
  { family: "Libre Baskerville", group: "Serif" },
  { family: "EB Garamond", group: "Serif" },
  { family: "Cormorant Garamond", group: "Serif" },
  { family: "DM Serif Display", group: "Serif" },
  { family: "Spectral", group: "Serif" },
  { family: "Source Serif 4", group: "Serif" },
  { family: "Crimson Pro", group: "Serif" },
  { family: "PT Serif", group: "Serif" },
  { family: "Noto Serif", group: "Serif" },
  { family: "Bitter", group: "Serif" },
  { family: "Literata", group: "Serif" },
  { family: "Fraunces", group: "Serif" },
  { family: "Cardo", group: "Serif" },
  { family: "Inter", group: "Sans" },
  { family: "Roboto", group: "Sans" },
  { family: "Open Sans", group: "Sans" },
  { family: "Lato", group: "Sans" },
  { family: "Montserrat", group: "Sans" },
  { family: "Raleway", group: "Sans" },
  { family: "Poppins", group: "Sans" },
  { family: "Nunito", group: "Sans" },
  { family: "Work Sans", group: "Sans" },
  { family: "DM Sans", group: "Sans" },
  { family: "Outfit", group: "Sans" },
  { family: "Manrope", group: "Sans" },
  { family: "Plus Jakarta Sans", group: "Sans" },
  { family: "Figtree", group: "Sans" },
  { family: "Sora", group: "Sans" },
  { family: "Lexend", group: "Sans" },
  { family: "Urbanist", group: "Sans" },
  { family: "Syne", group: "Sans" },
  { family: "Rubik", group: "Sans" },
  { family: "Quicksand", group: "Sans" },
  { family: "Karla", group: "Sans" },
  { family: "Mulish", group: "Sans" },
  { family: "Barlow", group: "Sans" },
  { family: "IBM Plex Sans", group: "Sans" },
  { family: "Bebas Neue", group: "Display" },
  { family: "Oswald", group: "Display" },
  { family: "Anton", group: "Display" },
  { family: "Righteous", group: "Display" },
  { family: "Archivo Black", group: "Display" },
  { family: "Abril Fatface", group: "Display" },
  { family: "Alfa Slab One", group: "Display" },
  { family: "Bungee", group: "Display" },
  { family: "Cinzel", group: "Display" },
  { family: "Fjalla One", group: "Display" },
  { family: "Staatliches", group: "Display" },
  { family: "Yeseva One", group: "Display" },
  { family: "Great Vibes", group: "Script" },
  { family: "Dancing Script", group: "Script" },
  { family: "Pacifico", group: "Script" },
  { family: "Satisfy", group: "Script" },
  { family: "Caveat", group: "Script" },
  { family: "Lobster", group: "Script" },
  { family: "Sacramento", group: "Script" },
  { family: "Allura", group: "Script" },
]
