import type {
  User,
  Reseller,
  EndUser,
  Package,
  Order,
  LiveEvent,
  WalletTransaction,
  PaymentGatewayConfig,
  Notification,
  AdminStats,
  ResellerStats,
  UserStats,
  WalletSummary,
  UserInventory,
  CustomPrice,
  ValidityPrice,
  EventTemplate,
  Domain,
  Payment,
  GatewayOption,
  Branding,
  EmailTemplate,
  YouTubeChannel,
  YouTubeBroadcast,
  FacebookPage,
  RefundRequest,
  WalletAdjustment,
  PaymentGatewayTransaction, // Import new types
  UnmatchedPayment, // Import new types
  GSTConfiguration, // Import new types
} from "./types"

// Mock Admin
export const mockAdmin: User = {
  id: "admin-1",
  email: "admin@streammattic.com",
  name: "Platform Admin",
  role: "admin",
  status: "active",
  createdAt: new Date("2024-01-01"),
  updatedAt: new Date(),
}

// Mock Resellers
export const mockResellers: Reseller[] = [
  {
    id: "reseller-1",
    email: "john@livestream.pro",
    name: "John's LiveStream Pro",
    phone: "+1234567890",
    role: "reseller",
    status: "active",
    walletBalance: 15000,
    totalEvents: 234,

    createdAt: new Date("2024-02-15"),
    updatedAt: new Date(),
    branding: {
      id: "brand-1",
  
      platformName: "LiveStream Pro",
      primaryColor: "#10b981",
      secondaryColor: "#059669",
      supportEmail: "support@livestream.pro",
    },
  },
  {
    id: "reseller-2",
    email: "sarah@streamhub.io",
    name: "StreamHub Media",
    phone: "+0987654321",
    role: "reseller",
    status: "active",
    walletBalance: 8500,
    totalEvents: 156,
    createdAt: new Date("2024-03-01"),
    updatedAt: new Date(),
    branding: {
      id: "brand-2",
      resellerId: "reseller-2",
      platformName: "StreamHub",
      primaryColor: "#3b82f6",
      secondaryColor: "#2563eb",
      supportEmail: "help@streamhub.io",
    },
  },
  {
    id: "reseller-3",
    email: "mike@eventcast.tv",
    name: "EventCast TV",
    role: "reseller",
    status: "inactive",
    walletBalance: 2200,
    totalEvents: 67,
    createdAt: new Date("2024-04-10"),
    updatedAt: new Date(),
    branding: {
      id: "brand-3",
      resellerId: "reseller-3",
      platformName: "EventCast",
      primaryColor: "#8b5cf6",
      secondaryColor: "#7c3aed",
    },
  },
  {
    id: "reseller-4",
    email: "priya@weddingstreams.in",
    name: "Wedding Streams India",
    phone: "+919876543210",
    role: "reseller",
    status: "active",
    walletBalance: 5000,
    totalEvents: 89,
    createdAt: new Date("2024-05-20"),
    updatedAt: new Date(),
    branding: {
      id: "brand-4",
      resellerId: "reseller-4",
      platformName: "Wedding Streams",
      primaryColor: "#ec4899",
      secondaryColor: "#db2777",
      supportEmail: "support@weddingstreams.in",
    },
  },
  {
    id: "reseller-5",
    email: "raj@corporateevents.co",
    name: "Corporate Events Co",
    phone: "+919123456789",
    role: "reseller",
    status: "active",
    walletBalance: 7500,
    totalEvents: 45,
    createdAt: new Date("2024-06-10"),
    updatedAt: new Date(),
    branding: {
      id: "brand-5",
      resellerId: "reseller-5",
      platformName: "Corporate Events",
      primaryColor: "#0ea5e9",
      secondaryColor: "#0284c7",
      supportEmail: "help@corporateevents.co",
    },
  },
]

// Mock End Users
export const mockUsers: EndUser[] = [
  {
    id: "user-1",
    email: "alice@example.com",
    name: "Alice Johnson",
    role: "user",
    status: "active",
    packageId: "pkg-2",
    packageExpiresAt: new Date("2025-02-15"),
    walletBalance: 500,
    totalEvents: 15,
    eventsUsed: 8,
    createdAt: new Date("2024-06-01"),
    updatedAt: new Date(),
  },
  {
    id: "user-2",
    email: "bob@example.com",
    name: "Bob Smith",
    role: "user",
    status: "active",
    packageId: "pkg-1",
    packageExpiresAt: new Date("2025-01-20"),
    walletBalance: 150,
    totalEvents: 5,
    eventsUsed: 5,
    createdAt: new Date("2024-07-15"),
    updatedAt: new Date(),
  },
  {
    id: "user-3",
    email: "charlie@example.com",
    name: "Charlie Brown",
    role: "user",
    status: "suspended",
    walletBalance: 0,
    totalEvents: 3,
    eventsUsed: 3,
    createdAt: new Date("2024-08-01"),
    updatedAt: new Date(),
  },
]

// Mock Packages
export const mockPackages: Package[] = [
  {
    id: "pkg-1",
    name: "Starter",
    slug: "starter",
    type: "event_pack",
    pricingModel: "monthly",
    description: "Perfect for beginners",
    price: 999,
    basePriceReseller: 600,
    basePriceUser: 999,
    duration: 30,
    maxEvents: 5,
    maxConcurrentViewers: 100,
    features: ["5 Live Events", "100 Concurrent Viewers", "Basic Analytics", "Email Support"],
    isActive: true,
    sortOrder: 1,
    minQty: 1,
    maxQty: 10,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date(),
  },
  {
    id: "pkg-2",
    name: "Professional",
    slug: "professional",
    type: "event_pack",
    pricingModel: "monthly",
    description: "For growing creators",
    price: 2499,
    basePriceReseller: 1500,
    basePriceUser: 2499,
    duration: 30,
    maxEvents: 20,
    maxConcurrentViewers: 500,
    features: ["20 Live Events", "500 Concurrent Viewers", "Advanced Analytics", "Priority Support", "Custom Branding"],
    isActive: true,
    sortOrder: 2,
    minQty: 1,
    maxQty: 10,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date(),
  },
  {
    id: "pkg-3",
    name: "Enterprise",
    slug: "enterprise",
    type: "event_pack",
    pricingModel: "monthly",
    description: "For large organizations",
    price: 9999,
    basePriceReseller: 6000,
    basePriceUser: 9999,
    duration: 30,
    maxEvents: -1, // Unlimited
    maxConcurrentViewers: 5000,
    features: [
      "Unlimited Events",
      "5000 Concurrent Viewers",
      "Full Analytics Suite",
      "24/7 Support",
      "Custom Branding",
      "API Access",
      "White-label",
    ],
    isActive: true,
    sortOrder: 3,
    minQty: 1,
    maxQty: 5,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date(),
  },
  {
    id: "pkg-pay-per-event",
    name: "Pay Per Event",
    slug: "pay-per-event",
    type: "pay_per_event",
    pricingModel: "pay_per_event",
    description: "Pay only for what you use - no commitment",
    price: 0,
    basePriceReseller: 0,
    basePriceUser: 0,
    duration: 0,
    maxEvents: -1,
    maxConcurrentViewers: 5000,
    features: [
      "No Monthly Commitment",
      "Pay Per Stream Type",
      "All Stream Types Available",
      "Simulcast Support",
      "Up to 5000 Viewers",
      "Full Analytics",
    ],
    isActive: true,
    sortOrder: 0,
    minQty: 1,
    maxQty: 999,
    streamTypePricing: {
      rtmp: {
        adminCost: 500,
        resellerPrice: 700,
        userPrice: 1500,
      },
      youtube_api: {
        adminCost: 300,
        resellerPrice: 400,
        userPrice: 1000,
      },
      youtube_embed: {
        adminCost: 100,
        resellerPrice: 150,
        userPrice: 500,
      },
      third_party: {
        adminCost: 50,
        resellerPrice: 100,
        userPrice: 400,
      },
    },
    simulcastPricing: {
      youtube: {
        adminCost: 30,
        resellerPrice: 40,
        userPrice: 75,
      },
      facebook: {
        adminCost: 30,
        resellerPrice: 40,
        userPrice: 75,
      },
      customRtmp: {
        adminCost: 50,
        resellerPrice: 60,
        userPrice: 100,
      },
    },
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date(),
  },
]

// Mock Orders
export const mockOrders: Order[] = [
  {
    id: "order-1",
    orderNumber: "ORD-M1K8X-ABC1",
    userId: "user-1",
    user: mockUsers[0] as any,
    orderType: "package",
    status: "approved",
    unitPrice: 2499,
    quantity: 1,
    totalPrice: 2499,
    items: [
      {
        id: "item-1",
        orderId: "order-1",
        packageId: "pkg-2",
        package: mockPackages[1],
        quantity: 1,
        unitPrice: 2499,
        totalPrice: 2499,
      },
    ],
    paymentGateway: "razorpay",
    paymentId: "pay_xyz123",
    approverId: "reseller-1",
    approvedAt: new Date("2024-11-15"),
    createdAt: new Date("2024-11-15"),
    updatedAt: new Date(),
  },
  {
    id: "order-2",
    orderNumber: "ORD-N2L9Y-DEF2",
    userId: "user-2",
    user: mockUsers[1] as any,
    orderType: "package",
    status: "pending",
    unitPrice: 999,
    quantity: 2,
    totalPrice: 1998,
    items: [
      {
        id: "item-2",
        orderId: "order-2",
        packageId: "pkg-1",
        package: mockPackages[0],
        quantity: 2,
        unitPrice: 999,
        totalPrice: 1998,
      },
    ],
    createdAt: new Date("2024-12-01"),
    updatedAt: new Date(),
  },
  {
    id: "order-3",
    orderNumber: "ORD-O3M0Z-GHI3",
    userId: "user-3",
    user: mockUsers[2] as any,
    orderType: "package",
    status: "rejected",
    unitPrice: 9999,
    quantity: 1,
    totalPrice: 9999,
    items: [
      {
        id: "item-3",
        orderId: "order-3",
        packageId: "pkg-3",
        package: mockPackages[2],
        quantity: 1,
        unitPrice: 9999,
        totalPrice: 9999,
      },
    ],
    rejectionReason: "Payment verification failed",
    rejectedAt: new Date("2024-11-21"),
    createdAt: new Date("2024-11-20"),
    updatedAt: new Date(),
  },
  {
    id: "order-4",
    orderNumber: "ORD-P4N1A-JKL4",
    userId: "user-1",
    user: mockUsers[0] as any,
    orderType: "validity",
    status: "pending",
    unitPrice: 799,
    quantity: 1,
    totalPrice: 799,
    eventId: "event-1",
    validityDays: 30,
    createdAt: new Date("2024-12-02"),
    updatedAt: new Date(),
  },
]

// Mock Live Events
export const mockEvents: LiveEvent[] = [
  {
    id: "event-1",
    userId: "user-1",
    title: "Tech Conference 2024",
    description: "Annual technology conference featuring industry leaders",
    streamType: "rtmp",
    streamKey: "live_abc123xyz",
    rtmpUrl: "rtmp://stream.streammattic.com/live",
    status: "live",
    scheduledAt: new Date(),
    startedAt: new Date(),
    maxViewers: 500,
    currentViewers: 342,
    totalViews: 1250,
    isPasswordProtected: false,
    allowChat: true,
    allowReactions: true,
    createdAt: new Date("2024-11-01"),
    updatedAt: new Date(),
  },
  {
    id: "event-2",
    userId: "user-1",

    title: "Product Launch Webinar",
    description: "Exclusive product launch event",
    streamType: "youtube",
    youtubeUrl: "https://youtube.com/watch?v=dQw4w9WgXcQ",
    status: "scheduled",
    scheduledAt: new Date(Date.now() + 86400000 * 2),
    maxViewers: 500,
    currentViewers: 0,
    totalViews: 0,
    isPasswordProtected: true,
    password: "launch2024",
    allowChat: true,
    allowReactions: true,
    createdAt: new Date("2024-11-20"),
    updatedAt: new Date(),
  },
  {
    id: "event-3",
    userId: "user-2",

    title: "Music Festival Stream",
    description: "Live streaming from the music festival",
    streamType: "hls",
    hlsUrl: "https://cdn.streammattic.com/hls/event-3/playlist.m3u8",
    status: "completed",
    scheduledAt: new Date(Date.now() - 86400000 * 5),
    startedAt: new Date(Date.now() - 86400000 * 5),
    endedAt: new Date(Date.now() - 86400000 * 5 + 10800000),
    maxViewers: 100,
    currentViewers: 0,
    totalViews: 856,
    isPasswordProtected: false,
    allowChat: true,
    allowReactions: true,
    createdAt: new Date("2024-11-10"),
    updatedAt: new Date(),
  },
  {
    id: "event-4",
    userId: "user-1",

    title: "January 2025 Kickoff",
    description: "Start the year with a live event",
    streamType: "rtmp",
    streamKey: "live_jan2025",
    rtmpUrl: "rtmp://stream.streammattic.com/live",
    status: "completed",
    scheduledAt: new Date("2025-01-15T14:00:00"),
    startedAt: new Date("2025-01-15T14:00:00"),
    endedAt: new Date("2025-01-15T16:00:00"),
    maxViewers: 500,
    currentViewers: 0,
    totalViews: 1500,
    isPasswordProtected: false,
    allowChat: true,
    allowReactions: true,
    createdAt: new Date("2024-12-20"),
    updatedAt: new Date("2025-01-15"),
  },
  {
    id: "event-5",
    userId: "user-1",

    title: "February Workshop",
    description: "Educational workshop on streaming",
    streamType: "youtube",
    youtubeUrl: "https://youtube.com/watch?v=workshop2025",
    status: "scheduled",
    scheduledAt: new Date("2025-02-20T10:00:00"),
    maxViewers: 300,
    currentViewers: 0,
    totalViews: 0,
    isPasswordProtected: false,
    allowChat: true,
    allowReactions: true,
    createdAt: new Date("2025-01-10"),
    updatedAt: new Date("2025-01-10"),
  },
  {
    id: "event-6",
    userId: "user-2",

    title: "March Music Concert",
    description: "Live music performance",
    streamType: "hls",
    hlsUrl: "https://cdn.streammattic.com/hls/event-6/playlist.m3u8",
    status: "live",
    scheduledAt: new Date("2025-03-10T19:00:00"),
    startedAt: new Date("2025-03-10T19:00:00"),
    maxViewers: 1000,
    currentViewers: 750,
    totalViews: 2300,
    isPasswordProtected: false,
    allowChat: true,
    allowReactions: true,
    createdAt: new Date("2025-02-15"),
    updatedAt: new Date("2025-03-10"),
  },
  {
    id: "event-7",
    userId: "user-1",

    title: "April Product Demo",
    description: "New product demonstration",
    streamType: "rtmp",
    streamKey: "live_apr2025",
    rtmpUrl: "rtmp://stream.streammattic.com/live",
    status: "cancelled",
    scheduledAt: new Date("2025-04-05T13:00:00"),
    maxViewers: 200,
    currentViewers: 0,
    totalViews: 0,
    isPasswordProtected: false,
    allowChat: true,
    allowReactions: true,
    createdAt: new Date("2025-03-01"),
    updatedAt: new Date("2025-03-28"),
  },
  {
    id: "event-8",
    userId: "user-2",

    title: "May Gaming Tournament",
    description: "Annual gaming competition",
    streamType: "youtube",
    youtubeUrl: "https://youtube.com/watch?v=gaming2025",
    status: "scheduled",
    scheduledAt: new Date("2025-05-25T18:00:00"),
    maxViewers: 800,
    currentViewers: 0,
    totalViews: 0,
    isPasswordProtected: false,
    allowChat: true,
    allowReactions: true,
    createdAt: new Date("2025-04-10"),
    updatedAt: new Date("2025-04-10"),
  },
  {
    id: "event-9",
    userId: "user-1",

    title: "June Summer Festival",
    description: "Summer celebration event",
    streamType: "hls",
    hlsUrl: "https://cdn.streammattic.com/hls/event-9/playlist.m3u8",
    status: "completed",
    scheduledAt: new Date("2025-06-15T15:00:00"),
    startedAt: new Date("2025-06-15T15:00:00"),
    endedAt: new Date("2025-06-15T20:00:00"),
    maxViewers: 1200,
    currentViewers: 0,
    totalViews: 3500,
    isPasswordProtected: false,
    allowChat: true,
    allowReactions: true,
    createdAt: new Date("2025-05-01"),
    updatedAt: new Date("2025-06-15"),
  },
  {
    id: "event-10",
    userId: "user-1",

    title: "July Tech Talk",
    description: "Monthly tech discussion",
    streamType: "rtmp",
    streamKey: "live_jul2025",
    rtmpUrl: "rtmp://stream.streammattic.com/live",
    status: "live",
    scheduledAt: new Date("2025-07-08T11:00:00"),
    startedAt: new Date("2025-07-08T11:00:00"),
    maxViewers: 400,
    currentViewers: 320,
    totalViews: 980,
    isPasswordProtected: false,
    allowChat: true,
    allowReactions: true,
    createdAt: new Date("2025-06-20"),
    updatedAt: new Date("2025-07-08"),
  },
  {
    id: "event-11",
    userId: "user-2",

    title: "August Webinar Series",
    description: "Educational webinar",
    streamType: "youtube",
    youtubeUrl: "https://youtube.com/watch?v=webinar2025",
    status: "scheduled",
    scheduledAt: new Date("2025-08-12T14:30:00"),
    maxViewers: 350,
    currentViewers: 0,
    totalViews: 0,
    isPasswordProtected: true,
    password: "webinar2025",
    allowChat: true,
    allowReactions: true,
    createdAt: new Date("2025-07-15"),
    updatedAt: new Date("2025-07-15"),
  },
  {
    id: "event-12",
    userId: "user-1",

    title: "September Conference",
    description: "Fall conference and networking",
    streamType: "hls",
    hlsUrl: "https://cdn.streammattic.com/hls/event-12/playlist.m3u8",
    status: "completed",
    scheduledAt: new Date("2025-09-22T09:00:00"),
    startedAt: new Date("2025-09-22T09:00:00"),
    endedAt: new Date("2025-09-22T17:00:00"),
    maxViewers: 900,
    currentViewers: 0,
    totalViews: 4200,
    isPasswordProtected: false,
    allowChat: true,
    allowReactions: true,
    createdAt: new Date("2025-08-01"),
    updatedAt: new Date("2025-09-22"),
  },
  {
    id: "event-13",
    userId: "user-1",

    title: "January 2026 Launch",
    description: "New year product launch",
    streamType: "rtmp",
    streamKey: "live_jan2026",
    rtmpUrl: "rtmp://stream.streammattic.com/live",
    status: "scheduled",
    scheduledAt: new Date("2026-01-20T16:00:00"),
    maxViewers: 600,
    currentViewers: 0,
    totalViews: 0,
    isPasswordProtected: false,
    allowChat: true,
    allowReactions: true,
    createdAt: new Date("2025-12-10"),
    updatedAt: new Date("2025-12-10"),
  },
  {
    id: "event-14",
    userId: "user-2",

    title: "March 2026 Expo",
    description: "Industry expo and showcase",
    streamType: "youtube",
    youtubeUrl: "https://youtube.com/watch?v=expo2026",
    status: "scheduled",
    scheduledAt: new Date("2026-03-15T10:00:00"),
    maxViewers: 1000,
    currentViewers: 0,
    totalViews: 0,
    isPasswordProtected: false,
    allowChat: true,
    allowReactions: true,
    createdAt: new Date("2026-01-20"),
    updatedAt: new Date("2026-01-20"),
  },
  {
    id: "event-15",
    userId: "user-1",

    title: "June 2026 Summit",
    description: "Mid-year business summit",
    streamType: "hls",
    hlsUrl: "https://cdn.streammattic.com/hls/event-15/playlist.m3u8",
    status: "scheduled",
    scheduledAt: new Date("2026-06-10T13:00:00"),
    maxViewers: 800,
    currentViewers: 0,
    totalViews: 0,
    isPasswordProtected: true,
    password: "summit2026",
    allowChat: true,
    allowReactions: true,
    createdAt: new Date("2026-04-01"),
    updatedAt: new Date("2026-04-01"),
  },
  {
    id: "event-16",
    userId: "user-2",

    title: "September 2026 Festival",
    description: "Fall arts festival",
    streamType: "rtmp",
    streamKey: "live_sep2026",
    rtmpUrl: "rtmp://stream.streammattic.com/live",
    status: "scheduled",
    scheduledAt: new Date("2026-09-18T17:00:00"),
    maxViewers: 1500,
    currentViewers: 0,
    totalViews: 0,
    isPasswordProtected: false,
    allowChat: true,
    allowReactions: true,
    createdAt: new Date("2026-07-01"),
    updatedAt: new Date("2026-07-01"),
  },
  {
    id: "event-17",
    userId: "user-1",

    title: "December 2026 Finale",
    description: "Year-end celebration",
    streamType: "youtube",
    youtubeUrl: "https://youtube.com/watch?v=finale2026",
    status: "scheduled",
    scheduledAt: new Date("2026-12-20T19:00:00"),
    maxViewers: 2000,
    currentViewers: 0,
    totalViews: 0,
    isPasswordProtected: false,
    allowChat: true,
    allowReactions: true,
    createdAt: new Date("2026-10-15"),
    updatedAt: new Date("2026-10-15"),
  },
  {
    id: "event-18",
    userId: "user-1",

    title: "December Holiday Stream",
    description: "Holiday season kickoff",
    streamType: "rtmp",
    streamKey: "live_dec2025",
    rtmpUrl: "rtmp://stream.streammattic.com/live",
    status: "live",
    scheduledAt: new Date("2025-12-07T15:00:00"),
    startedAt: new Date("2025-12-07T15:00:00"),
    maxViewers: 650,
    currentViewers: 420,
    totalViews: 1100,
    isPasswordProtected: false,
    allowChat: true,
    allowReactions: true,
    createdAt: new Date("2025-11-20"),
    updatedAt: new Date("2025-12-07"),
  },
  {
    id: "event-19",
    userId: "user-1",

    title: "December Product Showcase",
    description: "Showcasing new products",
    streamType: "youtube",
    youtubeUrl: "https://youtube.com/watch?v=showcase2025",
    status: "scheduled",
    scheduledAt: new Date("2025-12-09T12:00:00"),
    maxViewers: 500,
    currentViewers: 0,
    totalViews: 0,
    isPasswordProtected: false,
    allowChat: true,
    allowReactions: true,
    createdAt: new Date("2025-11-25"),
    updatedAt: new Date("2025-11-25"),
  },
  {
    id: "event-20",
    userId: "user-1",

    title: "December Training Completed",
    description: "Staff training session finished",
    streamType: "hls",
    hlsUrl: "https://cdn.streammattic.com/hls/event-20/playlist.m3u8",
    status: "completed",
    scheduledAt: new Date("2025-12-09T09:00:00"),
    startedAt: new Date("2025-12-09T09:00:00"),
    endedAt: new Date("2025-12-09T11:00:00"),
    maxViewers: 200,
    currentViewers: 0,
    totalViews: 450,
    isPasswordProtected: false,
    allowChat: true,
    allowReactions: true,
    createdAt: new Date("2025-11-15"),
    updatedAt: new Date("2025-12-09"),
  },
  {
    id: "event-21",
    userId: "user-1",

    title: "December Live Workshop",
    description: "Interactive workshop session",
    streamType: "rtmp",
    streamKey: "live_workshop_dec",
    rtmpUrl: "rtmp://stream.streammattic.com/live",
    status: "live",
    scheduledAt: new Date("2025-12-09T14:00:00"),
    startedAt: new Date("2025-12-09T14:00:00"),
    maxViewers: 400,
    currentViewers: 280,
    totalViews: 720,
    isPasswordProtected: false,
    allowChat: true,
    allowReactions: true,
    createdAt: new Date("2025-11-28"),
    updatedAt: new Date("2025-12-09"),
  },
  {
    id: "event-22",
    userId: "user-1",

    title: "December Cancelled Event",
    description: "Event cancelled due to schedule conflict",
    streamType: "youtube",
    youtubeUrl: "https://youtube.com/watch?v=cancelled2025",
    status: "cancelled",
    scheduledAt: new Date("2025-12-09T18:00:00"),
    maxViewers: 300,
    currentViewers: 0,
    totalViews: 0,
    isPasswordProtected: false,
    allowChat: true,
    allowReactions: true,
    createdAt: new Date("2025-11-18"),
    updatedAt: new Date("2025-12-05"),
  },
]

// Mock Wallet Transactions
export const mockTransactions: WalletTransaction[] = [
  // Admin transactions
  {
    id: "txn-admin-1",
    walletId: "wallet-admin",
    userId: "admin-1",
    type: "credit",
    category: "top_up",
    amount: 100000,
    balanceBefore: 0,
    balanceAfter: 100000,
    description: "Initial platform balance",
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "txn-admin-2",
    walletId: "wallet-admin",
    userId: "admin-1",
    type: "debit",
    category: "cascade_debit",
    amount: 600,
    balanceBefore: 100000,
    balanceAfter: 99400,
    description: "Cascade debit - Professional Package (Reseller: LiveStream Pro)",
    referenceId: "order-1",
    referenceType: "ORDER",
    cascadeLevel: 2,
    createdAt: new Date("2024-11-15T10:30:00"),
  },
  // Reseller transactions
  {
    id: "txn-res-1",
    walletId: "wallet-reseller-1",
    userId: "reseller-1",
    type: "credit",
    category: "top_up",
    amount: 20000,
    balanceBefore: 0,
    balanceAfter: 20000,
    description: "Admin wallet top-up",
    referenceId: "admin-1",
    referenceType: "ADMIN_TOPUP",
    createdAt: new Date("2024-02-15"),
  },
  {
    id: "txn-res-2",
    walletId: "wallet-reseller-1",
    userId: "reseller-1",
    type: "debit",
    category: "platform_debit",
    amount: 1000,
    balanceBefore: 20000,
    balanceAfter: 19000,
    description: "Platform debit - Professional Package event streaming",
    referenceId: "event-1",
    referenceType: "EVENT",
    createdAt: new Date("2024-11-15T10:30:00"),
  },
  {
    id: "txn-res-3",
    walletId: "wallet-reseller-1",
    userId: "reseller-1",
    type: "debit",
    category: "platform_debit",
    amount: 500,
    balanceBefore: 19000,
    balanceAfter: 18500,
    description: "Platform debit - Starter Package event streaming",
    referenceId: "event-2",
    referenceType: "EVENT",
    createdAt: new Date("2024-12-01T14:20:00"),
  },
  {
    id: "txn-res-4",
    walletId: "wallet-reseller-1",
    userId: "reseller-1",
    type: "credit",
    category: "adjustment",
    amount: 1500,
    balanceBefore: 18500,
    balanceAfter: 20000,
    description: "Admin adjustment: Promotional bonus",
    referenceId: "admin-1",
    referenceType: "ADMIN_ADJUSTMENT",
    createdAt: new Date("2024-12-01T16:00:00"),
  },
  {
    id: "txn-res-5",
    walletId: "wallet-reseller-1",
    userId: "reseller-1",
    type: "debit",
    category: "ai_image_generation",
    amount: 500,
    balanceBefore: 20000,
    balanceAfter: 19500,
    description: "AI Image Generation - Hero Background",
    referenceId: "img-gen-1",
    referenceType: "AI_IMAGE",
    createdAt: new Date("2025-01-10T09:15:00"),
  },
  // User transactions
  {
    id: "txn-user-1",
    walletId: "wallet-user-1",
    userId: "user-1",
    type: "credit",
    category: "top_up",
    amount: 3000,
    balanceBefore: 0,
    balanceAfter: 3000,
    description: "Wallet top-up via Razorpay",
    referenceId: "pay_abc123",
    referenceType: "PAYMENT",
    createdAt: new Date("2024-11-10"),
  },
  {
    id: "txn-user-2",
    walletId: "wallet-user-1",
    userId: "user-1",
    type: "debit",
    category: "package_purchase",
    amount: 2499,
    balanceBefore: 3000,
    balanceAfter: 501,
    description: "Package purchase: Professional",
    referenceId: "order-1",
    referenceType: "ORDER",
    cascadeLevel: 0,
    createdAt: new Date("2024-11-15T10:30:00"),
  },
  {
    id: "txn-user-3",
    walletId: "wallet-user-1",
    userId: "user-1",
    type: "credit",
    category: "order_refund",
    amount: 999,
    balanceBefore: 501,
    balanceAfter: 1500,
    description: "Refund for cancelled order",
    referenceId: "order-cancelled",
    referenceType: "ORDER_REFUND",
    createdAt: new Date("2024-11-20"),
  },
]

export const mockWalletTransactions = mockTransactions

// Mock Payment Gateway Configs
export const mockPaymentGateways: PaymentGatewayConfig[] = [
  {
    id: "pg-1",
    gateway: "razorpay",
    isEnabled: true,
    isDefault: true,
    config: { key_id: "rzp_test_xxx", key_secret: "***" },
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date(),
  },
  {
    id: "pg-2",
    gateway: "instamojo",
    isEnabled: false,
    isDefault: false,
    config: {},
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date(),
  },
]

// Mock Notifications
export const mockNotifications: Notification[] = [
  {
    id: "notif-1",
    userId: "admin-1",
    title: "New Reseller Registration",
    message: "EventCast TV has registered as a new reseller",
    type: "info",
    isRead: false,
    link: "/admin/resellers",
    createdAt: new Date(),
  },
  {
    id: "notif-2",
    userId: "reseller-1",
    title: "Event Scheduled",
    message: "Your event 'Product Launch Webinar' has been scheduled for Dec 20",
    type: "info",
    isRead: false,
    link: "/reseller/events",
    createdAt: new Date(),
  },
  {
    id: "notif-3",
    userId: "reseller-1",
    title: "Wallet Top-Up Successful",
    message: "₹11,800 has been added to your wallet",
    type: "success",
    isRead: false,
    link: "/reseller/wallet",
    createdAt: new Date(Date.now() - 3600000),
  },
  {
    id: "notif-4",
    userId: "user-1",
    title: "Event Going Live",
    message: "Your event 'Tech Conference 2024' is now streaming",
    type: "success",
    isRead: true,
    readAt: new Date(Date.now() - 7200000),
    link: "/dashboard/events",
    createdAt: new Date(Date.now() - 7200000),
  },
  {
    id: "notif-5",
    userId: "user-1",
    title: "Low Wallet Balance",
    message: "Your wallet balance is below ₹500. Please recharge.",
    type: "warning",
    isRead: false,
    link: "/dashboard/wallet",
    createdAt: new Date(Date.now() - 86400000),
  },
  {
    id: "notif-6",
    userId: "reseller-1",
    title: "Domain Verified",
    message: "live.livestreampro.com has been verified successfully",
    type: "success",
    isRead: true,
    readAt: new Date(Date.now() - 172800000),
    link: "/reseller/domains",
    createdAt: new Date(Date.now() - 172800000),
  },
  {
    id: "notif-7",
    userId: "admin-1",
    title: "System Update",
    message: "Platform will undergo maintenance on Dec 15, 2024",
    type: "info",
    isRead: true,
    readAt: new Date(Date.now() - 259200000),
    createdAt: new Date(Date.now() - 259200000),
  },
]

// Mock Stats
export const mockAdminStats: AdminStats = {
  totalRevenue: 245000,
  totalResellers: 3,
  totalUsers: 85,
  totalEvents: 457,
  activeEvents: 12,
  pendingOrders: 8,
  revenueGrowth: 23.5,
  userGrowth: 15.2,
}

export const mockResellerStats: ResellerStats = {
  walletBalance: 15000,
  totalEvents: 234,
  activeEvents: 5,
  pendingOrders: 3,
  monthlyRevenue: 28500,
}

export const mockUserStats: UserStats = {
  walletBalance: 500,
  totalEvents: 15,
  activeEvents: 1,
  totalViews: 4250,
  packageName: "Professional",
  packageExpiry: new Date("2025-02-15"),
  eventsRemaining: 12,
}

// Mock Wallet Summaries
export const mockAdminWalletSummary: WalletSummary = {
  balance: 99400,
  totalCredits: 100000,
  totalDebits: 600,
  pendingAmount: 0,
  lastTransaction: mockTransactions[1],
}

export const mockResellerWalletSummary: WalletSummary = {
  balance: 15000,
  totalCredits: 21500,
  totalDebits: 6500,
  pendingAmount: 0,
  lastTransaction: mockTransactions[5],
}

export const mockUserWalletSummary: WalletSummary = {
  balance: 10000,
  totalCredits: 13499,
  totalDebits: 3499,
  pendingAmount: 0,
  lastTransaction: mockTransactions[8],
}

// Mock User Inventory
export const mockUserInventory: UserInventory[] = [
  {
    id: "inv-1",
    userId: "user-1",
    packageId: "pkg-2",
    package: mockPackages[1],
    totalQty: 20,
    availableQty: 12,
    usedQty: 8,
    createdAt: new Date("2024-11-15"),
    updatedAt: new Date(),
  },
  {
    id: "inv-2",
    userId: "user-2",
    packageId: "pkg-1",
    package: mockPackages[0],
    totalQty: 5,
    availableQty: 0,
    usedQty: 5,
    createdAt: new Date("2024-10-20"),
    updatedAt: new Date(),
  },
]

// Mock Custom Prices
export const mockCustomPrices: CustomPrice[] = [
  {
    id: "cp-1",
    packageId: "pkg-2",
    ownerId: "user-1",
    setById: "reseller-1",
    price: 2200, // Discounted from 2499
    createdAt: new Date("2024-11-01"),
    updatedAt: new Date(),
  },
]

// Mock Validity Prices
export const mockValidityPrices: ValidityPrice[] = [
  { id: "vp-1", packageId: "pkg-1", days: 7, priceReseller: 199, priceUser: 299, isActive: true },
  { id: "vp-2", packageId: "pkg-1", days: 30, priceReseller: 599, priceUser: 799, isActive: true },
  { id: "vp-3", packageId: "pkg-1", days: 90, priceReseller: 1499, priceUser: 1999, isActive: true },
  { id: "vp-4", packageId: "pkg-2", days: 7, priceReseller: 399, priceUser: 599, isActive: true },
  { id: "vp-5", packageId: "pkg-2", days: 30, priceReseller: 999, priceUser: 1499, isActive: true },
  { id: "vp-6", packageId: "pkg-2", days: 90, priceReseller: 2499, priceUser: 3499, isActive: true },
]

// Mock Event Templates
export const mockEventTemplates: EventTemplate[] = [
  {
    id: "tpl-default",
    name: "Default",
    thumbnail: "/templates/default-template.jpg",
    category: "General",
    isActive: true,
    sortOrder: 1,
  },
  {
    id: "tpl-wedding",
    name: "Wedding",
    thumbnail: "/templates/wedding-template.jpg",
    category: "Wedding",
    isActive: true,
    sortOrder: 2,
  },
  {
    id: "tpl-corporate",
    name: "Corporate Event",
    thumbnail: "/templates/corporate-template.jpg",
    category: "Corporate",
    isActive: true,
    sortOrder: 3,
  },
  {
    id: "tpl-concert",
    name: "Music Concert",
    thumbnail: "/templates/concert-template.jpg",
    category: "Entertainment",
    isActive: true,
    sortOrder: 4,
  },
  {
    id: "tpl-christian",
    name: "Christian Ceremony",
    thumbnail: "/templates/christian-template.jpg",
    category: "Religious",
    isActive: true,
    sortOrder: 5,
  },
  {
    id: "tpl-muslim",
    name: "Islamic Ceremony",
    thumbnail: "/templates/muslim-template.jpg",
    category: "Religious",
    isActive: true,
    sortOrder: 6,
  },
  {
    id: "tpl-hindu",
    name: "Hindu Ceremony",
    thumbnail: "/templates/hindu-template.jpg",
    category: "Religious",
    isActive: true,
    sortOrder: 7,
  },
  {
    id: "tpl-sports",
    name: "Sports Event",
    thumbnail: "/templates/sports-template.jpg",
    category: "Sports",
    isActive: true,
    sortOrder: 8,
  },
  {
    id: "tpl-political",
    name: "Political Event",
    thumbnail: "/templates/political-template.jpg",
    category: "Political",
    isActive: true,
    sortOrder: 9,
  },
  {
    id: "tpl-school",
    name: "School Event",
    thumbnail: "/templates/school-template.jpg",
    category: "Education",
    isActive: true,
    sortOrder: 10,
  },
  {
    id: "tpl-birthday",
    name: "Birthday",
    thumbnail: "/templates/birthday-template.jpg",
    category: "Celebration",
    isActive: true,
    sortOrder: 11,
  },
  {
    id: "tpl-funeral",
    name: "Memorial Service",
    thumbnail: "/templates/funeral-template.jpg",
    category: "Memorial",
    isActive: true,
    sortOrder: 12,
  },
  {
    id: "tpl-indian-festival",
    name: "Indian Festival",
    thumbnail: "/templates/indian-festival-template.jpg",
    category: "Cultural",
    isActive: true,
    sortOrder: 13,
  },
  // Entertainment & Media
  {
    id: "tpl-gaming",
    name: "Gaming/Esports",
    thumbnail: "/templates/gaming-template.jpg",
    category: "Entertainment",
    isActive: true,
    sortOrder: 14,
  },
  {
    id: "tpl-podcast",
    name: "Podcast/Talk Show",
    thumbnail: "/templates/podcast-template.jpg",
    category: "Entertainment",
    isActive: true,
    sortOrder: 15,
  },
  {
    id: "tpl-movie-premiere",
    name: "Movie Premiere",
    thumbnail: "/templates/movie-premiere-template.jpg",
    category: "Entertainment",
    isActive: true,
    sortOrder: 16,
  },
  {
    id: "tpl-award-ceremony",
    name: "Award Ceremony",
    thumbnail: "/templates/award-ceremony-template.jpg",
    category: "Entertainment",
    isActive: true,
    sortOrder: 17,
  },
  {
    id: "tpl-comedy-show",
    name: "Comedy Show",
    thumbnail: "/templates/comedy-show-template.jpg",
    category: "Entertainment",
    isActive: true,
    sortOrder: 18,
  },
  // Business & Professional
  {
    id: "tpl-product-launch",
    name: "Product Launch",
    thumbnail: "/templates/product-launch-template.jpg",
    category: "Business",
    isActive: true,
    sortOrder: 19,
  },
  {
    id: "tpl-webinar",
    name: "Webinar/Training",
    thumbnail: "/templates/webinar-template.jpg",
    category: "Business",
    isActive: true,
    sortOrder: 20,
  },
  {
    id: "tpl-auction",
    name: "Live Auction",
    thumbnail: "/templates/auction-template.jpg",
    category: "Business",
    isActive: true,
    sortOrder: 21,
  },
  {
    id: "tpl-real-estate",
    name: "Real Estate Tour",
    thumbnail: "/templates/real-estate-template.jpg",
    category: "Business",
    isActive: true,
    sortOrder: 22,
  },
  // Social & Community
  {
    id: "tpl-baby-shower",
    name: "Baby Shower",
    thumbnail: "/templates/baby-shower-template.jpg",
    category: "Celebration",
    isActive: true,
    sortOrder: 23,
  },
  {
    id: "tpl-graduation",
    name: "Graduation",
    thumbnail: "/templates/graduation-template.jpg",
    category: "Education",
    isActive: true,
    sortOrder: 24,
  },
  {
    id: "tpl-engagement",
    name: "Engagement Party",
    thumbnail: "/templates/engagement-template.jpg",
    category: "Celebration",
    isActive: true,
    sortOrder: 25,
  },
  {
    id: "tpl-anniversary",
    name: "Anniversary",
    thumbnail: "/templates/anniversary-template.jpg",
    category: "Celebration",
    isActive: true,
    sortOrder: 26,
  },
  {
    id: "tpl-reunion",
    name: "Reunion",
    thumbnail: "/templates/reunion-template.jpg",
    category: "Social",
    isActive: true,
    sortOrder: 27,
  },
  // Cultural & Regional
  {
    id: "tpl-chinese-festival",
    name: "Chinese Festival",
    thumbnail: "/templates/chinese-festival-template.jpg",
    category: "Cultural",
    isActive: true,
    sortOrder: 28,
  },
  {
    id: "tpl-christmas",
    name: "Christmas",
    thumbnail: "/templates/christmas-template.jpg",
    category: "Cultural",
    isActive: true,
    sortOrder: 29,
  },
  {
    id: "tpl-eid",
    name: "Eid Celebration",
    thumbnail: "/templates/eid-template.jpg",
    category: "Cultural",
    isActive: true,
    sortOrder: 30,
  },
  {
    id: "tpl-thanksgiving",
    name: "Thanksgiving",
    thumbnail: "/templates/thanksgiving-template.jpg",
    category: "Cultural",
    isActive: true,
    sortOrder: 31,
  },
  {
    id: "tpl-halloween",
    name: "Halloween",
    thumbnail: "/templates/halloween-template.jpg",
    category: "Cultural",
    isActive: true,
    sortOrder: 32,
  },
  // Health & Wellness
  {
    id: "tpl-fitness",
    name: "Fitness/Workout",
    thumbnail: "/templates/fitness-template.jpg",
    category: "Health",
    isActive: true,
    sortOrder: 33,
  },
  {
    id: "tpl-yoga",
    name: "Yoga/Meditation",
    thumbnail: "/templates/yoga-template.jpg",
    category: "Health",
    isActive: true,
    sortOrder: 34,
  },
  {
    id: "tpl-charity",
    name: "Charity/Fundraiser",
    thumbnail: "/templates/charity-template.jpg",
    category: "Social",
    isActive: true,
    sortOrder: 35,
  },
]

// Mock Domains
export const mockDomains: Domain[] = [
  {
    id: "dom-1",
    userId: "reseller-1",
    domain: "live.livestreampro.com",
    verificationToken: "streammattic-verify-abc123xyz456",
    verificationStatus: "verified",
    sslStatus: "active",
    isPrimary: true,
    verifiedAt: new Date("2024-06-01"),
    createdAt: new Date("2024-05-28"),
  },
  {
    id: "dom-2",
    userId: "reseller-1",
    domain: "events.livestreampro.com",
    verificationToken: "streammattic-verify-def789ghi012",
    verificationStatus: "pending",
    sslStatus: "pending",
    isPrimary: false,
    createdAt: new Date("2024-11-15"),
  },
  {
    id: "dom-3",
    userId: "reseller-2",
    domain: "stream.streamhub.io",
    verificationToken: "streammattic-verify-jkl345mno678",
    verificationStatus: "verified",
    sslStatus: "active",
    isPrimary: true,
    verifiedAt: new Date("2024-07-10"),
    createdAt: new Date("2024-07-05"),
  },
]

// Mock Payments
export const mockPayments: Payment[] = [
  {
    id: "pay-1",
    userId: "reseller-1",
    orderNumber: "PAY-M1K8X-ABC1",
    amount: 10000,
    gstAmount: 1800,
    totalAmount: 11800,
    gateway: "razorpay",
    status: "success",
    gatewayOrderId: "order_abc123",
    gatewayPaymentId: "pay_xyz789",
    paidAt: new Date("2024-11-10"),
    createdAt: new Date("2024-11-10"),
  },
  {
    id: "pay-2",
    userId: "reseller-1",
    orderNumber: "PAY-N2L9Y-DEF2",
    amount: 5000,
    gstAmount: 900,
    totalAmount: 5900,
    gateway: "instamojo",
    status: "success",
    gatewayOrderId: "im_order_456",
    gatewayPaymentId: "MOJO12345",
    paidAt: new Date("2024-12-01"),
    createdAt: new Date("2024-12-01"),
  },
  {
    id: "pay-3",
    userId: "user-1",
    orderNumber: "PAY-O3M0Z-GHI3",
    amount: 3000,
    gstAmount: 540,
    totalAmount: 3540,
    gateway: "razorpay",
    status: "pending",
    gatewayOrderId: "order_pending123",
    createdAt: new Date("2024-12-02"),
  },
]

// Mock Gateway Options
export const mockGatewayOptions: GatewayOption[] = [
  {
    id: "razorpay",
    name: "Razorpay",
    logo: "/razorpay-logo.jpg",
    description: "Pay with UPI, Cards, Netbanking",
    isEnabled: true,
  },
  {
    id: "instamojo",
    name: "Instamojo",
    logo: "/instamojo-logo.jpg",
    description: "Simple payments for everyone",
    isEnabled: true,
  },
  {
    id: "cashfree",
    name: "Cashfree",
    logo: "/cashfree-logo.png",
    description: "Fast & secure payments",
    isEnabled: true,
  },
]

// Mock Branding
export const mockBranding: Branding = {
  id: "brand-1",
  userId: "reseller-1",
  brandName: "LiveStream Pro",
  companyLogo: "/livestream-pro-logo.jpg",
  companyLogoDark: "/livestream-pro-logo-dark.jpg",
  favicon: "/website-favicon.png",
  themeColor: "#10b981",
  accentColor: "#059669",
  email: "support@livestream.pro",
  phone: "+1 (555) 123-4567",
  whatsapp: "+1 (555) 123-4567",
  address: "123 Streaming Lane, Digital City, DC 10001",
  facebookUrl: "https://facebook.com/livestreampro",
  instagramUrl: "https://instagram.com/livestreampro",
  twitterUrl: "https://twitter.com/livestreampro",
  youtubeUrl: "https://youtube.com/livestreampro",
  linkedinUrl: "https://linkedin.com/company/livestreampro",
  metaTitle: "LiveStream Pro - Professional Live Streaming Platform",
  metaDescription: "Stream your events with professional quality. Weddings, conferences, concerts and more.",
  googleAnalyticsId: "G-XXXXXXXXXX",
  aboutUs: "LiveStream Pro is a leading provider of professional live streaming services for events of all sizes.",
  termsConditions: "Terms and conditions content goes here...",
  privacyPolicy: "Privacy policy content goes here...",
  refundPolicy: "Refund policy content goes here...",
  preferredGateway: "razorpay",
  hasGatewayConfig: true,
  heroImage: "https://v3b.fal.media/files/b/0a9050f0/SroZCGJykTGOESyeDyNWY.jpg",
  aboutImage: "https://v3b.fal.media/files/b/0a9050f0/f-_58kA7Ac84zxbTd1RV1.jpg",
  services: [
    {
      id: "svc-1",
      title: "Photography",
      description: "Pre-wedding, wedding day, event & portrait photography with cinematic quality and attention to detail.",
      icon: "Camera",
      enabled: true,
    },
    {
      id: "svc-2",
      title: "Videography",
      description: "Cinematic wedding films, event highlights, reels & trailers that capture every emotion beautifully.",
      icon: "Film",
      enabled: true,
    },
    {
      id: "svc-3",
      title: "Live Streaming",
      description: "Let distant family & friends watch your event live from anywhere in the world in HD quality.",
      icon: "Radio",
      enabled: true,
    },
    {
      id: "svc-4",
      title: "Drone / Aerial",
      description: "Stunning aerial shots of your venue and event from breathtaking perspectives.",
      icon: "Plane",
      enabled: true,
    },
  ],
  eventTypes: [
    { id: "evt-1", title: "Weddings", image: "https://v3b.fal.media/files/b/0a9050ef/2giwMCCfP_4xgUx-x_8R7.jpg", enabled: true },
    { id: "evt-2", title: "Corporate Events", image: "https://v3b.fal.media/files/b/0a9050ef/EPt7_h-st_Ufv6UEiqi2r.jpg", enabled: true },
    { id: "evt-3", title: "Birthdays & Parties", image: "https://v3b.fal.media/files/b/0a9050ef/iej-KDKYRRGhXoUuRXVIb.jpg", enabled: true },
    { id: "evt-4", title: "Private Events", image: "https://v3b.fal.media/files/b/0a9050ef/WXGsOEOs8P0RB9yANOz0p.jpg", enabled: true },
  ],
  stats: [
    { id: "stat-1", value: "500+", label: "Events Covered" },
    { id: "stat-2", value: "200+", label: "Weddings" },
    { id: "stat-3", value: "50+", label: "Corporate Events" },
  ],
  testimonials: [
    {
      id: "test-1",
      quote: "The photos and live stream were both incredible. Our relatives in the US felt like they were right there at the wedding. Truly professional!",
      name: "Priya & Rahul",
      eventType: "Wedding",
      location: "Mumbai",
    },
    {
      id: "test-2",
      quote: "They handled our entire corporate event -- photography, videography, and live streaming to 3 offices. Seamless execution.",
      name: "Ankit Mehta",
      eventType: "Corporate Event",
      location: "Bangalore",
    },
    {
      id: "test-3",
      quote: "Our son's first birthday was captured beautifully. The drone shots of the outdoor venue were the highlight!",
      name: "Sneha & Vikram",
      eventType: "Birthday",
      location: "Delhi",
    },
  ],
  galleryImages: [
    { id: "gal-1", src: "https://v3b.fal.media/files/b/0a9050ef/PHKIxrRtt2ndiQLO-CE2z.jpg", title: "Sharma Wedding", category: "Weddings" },
    { id: "gal-2", src: "https://v3b.fal.media/files/b/0a9050ef/EEOvAyZeZyqM8oS9s-ZgG.jpg", title: "TechCon 2024", category: "Corporate Events" },
    { id: "gal-3", src: "https://v3b.fal.media/files/b/0a9050ef/s68MxjjRBL_DILOM1GS1r.jpg", title: "Arjun's 1st Birthday", category: "Birthdays & Parties" },
    { id: "gal-4", src: "https://v3b.fal.media/files/b/0a9050ef/SNJHCSk3mduvB89ABrIFk.jpg", title: "Gupta Reception", category: "Weddings" },
    { id: "gal-5", src: "https://v3b.fal.media/files/b/0a9050f0/1_bhTw0SsVMjO4l_luR-x.jpg", title: "Annual Meetup 2024", category: "Corporate Events" },
    { id: "gal-6", src: "https://v3b.fal.media/files/b/0a9050f0/AKJJzIfGmtMbiXRaaslA3.jpg", title: "Housewarming Ceremony", category: "Private Events" },
  ],
  createdAt: new Date("2024-02-15"),
  updatedAt: new Date(),
}

// Mock Email Templates
export const mockEmailTemplates: EmailTemplate[] = [
  {
    id: "tpl-email-1",
    type: "welcome",
    name: "Welcome Email",
    subject: "Welcome to {{brandName}}!",
    description: "Sent when a new user registers",
    variables: ["name", "brandName", "loginUrl"],
  },
  {
    id: "tpl-email-2",
    type: "order_confirmation",
    name: "Order Confirmation",
    subject: "Order {{orderNumber}} - {{status}}",
    description: "Sent when an order is placed",
    variables: ["name", "orderNumber", "type", "quantity", "total", "status"],
  },
  {
    id: "tpl-email-3",
    type: "payment_success",
    name: "Payment Success",
    subject: "Payment Successful - ₹{{total}}",
    description: "Sent when payment is completed",
    variables: ["name", "orderNumber", "amount", "gst", "total", "gateway"],
  },
  {
    id: "tpl-email-4",
    type: "approval_request",
    name: "Approval Request",
    subject: "Approval Required - Order {{orderNumber}}",
    description: "Sent to approver when order needs approval",
    variables: ["approverName", "orderNumber", "buyerName", "type", "total", "approvalUrl"],
  },
  {
    id: "tpl-email-5",
    type: "event_created",
    name: "Event Created",
    subject: "Event Created - {{title}}",
    description: "Sent when a new event is created",
    variables: ["name", "title", "date", "streamKey", "rtmpUrl", "eventUrl"],
  },
  {
    id: "tpl-email-6",
    type: "event_live",
    name: "Event Live",
    subject: "🔴 LIVE NOW - {{title}}",
    description: "Sent when event goes live",
    variables: ["name", "title", "eventUrl"],
  },
  {
    id: "tpl-email-7",
    type: "password_reset",
    name: "Password Reset",
    subject: "Reset Your Password",
    description: "Sent for password reset requests",
    variables: ["name", "resetUrl"],
  },
  {
    id: "tpl-email-8",
    type: "order_approved",
    name: "Order Approved",
    subject: "Order Approved - {{orderNumber}}",
    description: "Sent when order is approved",
    variables: ["name", "orderNumber", "type", "total"],
  },
  {
    id: "tpl-email-9",
    type: "order_rejected",
    name: "Order Rejected",
    subject: "Order Rejected - {{orderNumber}}",
    description: "Sent when order is rejected",
    variables: ["name", "orderNumber", "reason"],
  },
  {
    id: "tpl-email-10",
    type: "low_balance",
    name: "Low Balance Warning",
    subject: "Low Wallet Balance",
    description: "Sent when wallet balance is low",
    variables: ["name", "balance", "rechargeUrl"],
  },
  {
    id: "tpl-email-11",
    type: "event_expiring",
    name: "Event Expiring",
    subject: "Event Expiring - {{title}}",
    description: "Sent when event validity is expiring",
    variables: ["name", "title", "expiresAt", "extendUrl"],
  },
]

// Mock YouTube Channels and Broadcasts
export const mockYouTubeChannels: YouTubeChannel[] = [
  {
    id: "yt-chan-1",
    ownerId: "reseller-1",
    ownerType: "reseller",
    channelId: "UC1234567890",
    channelTitle: "John's LiveStream Pro",
    channelThumbnail: "/youtube-channel-avatar.png",
    accessToken: "mock-access-token-1",
    refreshToken: "mock-refresh-token-1",
    tokenExpiresAt: new Date(Date.now() + 3600000),
    isActive: true,
    createdAt: new Date("2024-02-15"),
    updatedAt: new Date(),
  },
  {
    id: "yt-chan-2",
    ownerId: "reseller-2",
    ownerType: "reseller",
    channelId: "UC9876543210",
    channelTitle: "StreamHub Media",
    channelThumbnail: "/streaming-channel-logo.jpg",
    accessToken: "mock-access-token-2",
    refreshToken: "mock-refresh-token-2",
    tokenExpiresAt: new Date(Date.now() + 3600000),
    isActive: true,
    createdAt: new Date("2024-03-01"),
    updatedAt: new Date(),
  },
]

export const mockYouTubeBroadcasts: YouTubeBroadcast[] = [
  {
    id: "yt-bcast-1",
    channelId: "UC1234567890",
    broadcastId: "BC1234567890",
    title: "Tech Conference 2024",
    description: "Annual technology conference featuring industry leaders",
    status: "active",
    scheduledAt: new Date(),
    startedAt: new Date(),
    endedAt: null,
    createdAt: new Date("2024-11-01"),
    updatedAt: new Date(),
  },
  {
    id: "yt-bcast-2",
    channelId: "UC9876543210",
    broadcastId: "BC9876543210",
    title: "Music Festival Stream",
    description: "Live streaming from the music festival",
    status: "completed",
    scheduledAt: new Date(Date.now() - 86400000 * 5),
    startedAt: new Date(Date.now() - 86400000 * 5),
    endedAt: new Date(Date.now() - 86400000 * 5 + 10800000),
    createdAt: new Date("2024-11-10"),
    updatedAt: new Date(),
  },
]

// Mock Facebook Pages
export const mockFacebookPages: FacebookPage[] = [
  {
    id: "fb-page-1",
    ownerId: "user-1",
    ownerType: "user",
    pageId: "123456789",
    pageName: "StreamMattic Events",
    pageThumbnail: "/facebook-page-logo.jpg",
    accessToken: "mock-fb-access-token-1",
    tokenExpiresAt: new Date(Date.now() + 86400000 * 60),
    isActive: true,
    createdAt: new Date("2024-10-01"),
    updatedAt: new Date(),
  },
  {
    id: "fb-page-2",
    ownerId: "user-1",
    ownerType: "user",
    pageId: "987654321",
    pageName: "Tech Conference Live",
    pageThumbnail: "/tech-conference-logo.png",
    accessToken: "mock-fb-access-token-2",
    tokenExpiresAt: new Date(Date.now() + 86400000 * 60),
    isActive: true,
    createdAt: new Date("2024-11-15"),
    updatedAt: new Date(),
  },
]

export const mockRefundRequests: RefundRequest[] = [
  {
    id: "ref_001",
    type: "event_cancellation",
    eventId: "event-7", // April Product Demo (cancelled)
    originalAmount: 1500,
    refundAmount: 1500,
    gstAmount: 270,
    totalRefundAmount: 1770,
    cascadeTransactionIds: ["txn_cascade_001", "txn_cascade_002"],
    status: "pending",
    requestedBy: "user-1",
    requestedByRole: "user",
    requestedAt: new Date("2025-03-28T10:00:00"),
    refundMethod: "wallet",
    createdAt: new Date("2025-03-28T10:00:00"),
    updatedAt: new Date("2025-03-28T10:00:00"),
  },
  {
    id: "ref_002",
    type: "event_cancellation",
    eventId: "event-2",
    originalAmount: 1000,
    refundAmount: 1000,
    gstAmount: 180,
    totalRefundAmount: 1180,
    cascadeTransactionIds: ["txn_cascade_003"],
    status: "approved",
    requestedBy: "user-1",
    requestedByRole: "user",
    requestedAt: new Date("2025-12-01T14:30:00"),
    approvedBy: "admin-1",
    approvedAt: new Date("2025-12-02T09:00:00"),
    refundMethod: "wallet",
    createdAt: new Date("2025-12-01T14:30:00"),
    updatedAt: new Date("2025-12-02T09:00:00"),
  },
  {
    id: "ref_003",
    type: "event_cancellation",
    eventId: "event-5",
    originalAmount: 1500,
    refundAmount: 750,
    gstAmount: 135,
    totalRefundAmount: 885,
    cascadeTransactionIds: ["txn_cascade_004"],
    status: "rejected",
    requestedBy: "user-2",
    requestedByRole: "user",
    requestedAt: new Date("2025-02-19T16:00:00"),
    rejectedBy: "admin-1",
    rejectedAt: new Date("2025-02-20T10:00:00"),
    rejectionReason: "Event is less than 24 hours away, only 50% refund eligible. User withdrew request.",
    refundMethod: "wallet",
    createdAt: new Date("2025-02-19T16:00:00"),
    updatedAt: new Date("2025-02-20T10:00:00"),
  },
]

export const mockWalletAdjustments: WalletAdjustment[] = [
  {
    id: "adj_001",
    targetUserId: "user-1",
    targetUserType: "user",
    type: "credit",
    amount: 5000,
    reason: "Payment gateway success but wallet credit failed - Razorpay pay_ABC123",
    category: "payment_recovery",
    initiatedBy: "admin-1",
    initiatedAt: new Date("2025-12-05T11:30:00"),
    approvalRequired: false,
    approvedBy: "admin-1",
    approvedAt: new Date("2025-12-05T11:30:00"),
    transactionId: "txn_adj_001",
    paymentGatewayId: "pay_ABC123",
    paymentGateway: "razorpay",
    supportTicketId: "ticket_1234",
    createdAt: new Date("2025-12-05T11:30:00"),
    updatedAt: new Date("2025-12-05T11:30:00"),
  },
  {
    id: "adj_002",
    targetUserId: "user-2",
    targetUserType: "user",
    type: "credit",
    amount: 1000,
    reason: "Compensation for service downtime on Dec 3",
    category: "compensation",
    initiatedBy: "admin-1",
    initiatedAt: new Date("2025-12-04T15:00:00"),
    approvalRequired: false,
    approvedBy: "admin-1",
    approvedAt: new Date("2025-12-04T15:00:00"),
    transactionId: "txn_adj_002",
    notes: "3 hours of downtime affected user's scheduled event",
    createdAt: new Date("2025-12-04T15:00:00"),
    updatedAt: new Date("2025-12-04T15:00:00"),
  },
  {
    id: "adj_003",
    targetUserId: "reseller-2",
    targetUserType: "reseller",
    type: "debit",
    amount: 500,
    reason: "Correction for duplicate credit on Nov 30",
    category: "correction",
    initiatedBy: "admin-1",
    initiatedAt: new Date("2025-12-01T09:00:00"),
    approvalRequired: false,
    approvedBy: "admin-1",
    approvedAt: new Date("2025-12-01T09:00:00"),
    transactionId: "txn_adj_003",
    notes: "Duplicate transaction due to payment gateway callback error",
    createdAt: new Date("2025-12-01T09:00:00"),
    updatedAt: new Date("2025-12-01T09:00:00"),
  },
]

// Mock Payment Gateway Transactions
export const mockPaymentGatewayTransactions: PaymentGatewayTransaction[] = [
  {
    id: "pgt_001",
    paymentId: "pay_razorpay_ABC123",
    gateway: "razorpay",
    userId: "user_001",
    userName: "Alice Johnson",
    userEmail: "alice@example.com",
    amount: 5000,
    gstAmount: 900,
    totalAmount: 5900,
    status: "success",
    walletTransactionId: "txn_wallet_001",
    createdAt: new Date("2025-12-01T10:00:00"),
    paidAt: new Date("2025-12-01T10:00:15"),
  },
  {
    id: "pgt_002",
    paymentId: "pay_instamojo_XYZ789",
    gateway: "instamojo",
    userId: "user_002",
    userName: "Bob Smith",
    userEmail: "bob@example.com",
    amount: 10000,
    gstAmount: 1800,
    totalAmount: 11800,
    status: "success",
    walletTransactionId: "txn_wallet_002",
    createdAt: new Date("2025-12-02T14:30:00"),
    paidAt: new Date("2025-12-02T14:30:20"),
  },
  {
    id: "pgt_003",
    paymentId: "pay_cashfree_DEF456",
    gateway: "cashfree",
    userId: "reseller_001",
    userName: "Tech Reseller Co",
    userEmail: "contact@techreseller.com",
    amount: 50000,
    gstAmount: 9000,
    totalAmount: 59000,
    status: "success",
    walletTransactionId: "txn_wallet_003",
    createdAt: new Date("2025-12-03T09:15:00"),
    paidAt: new Date("2025-12-03T09:15:30"),
  },
  {
    id: "pgt_004",
    paymentId: "pay_razorpay_FAIL001",
    gateway: "razorpay",
    userId: "user_003",
    userName: "Charlie Brown",
    userEmail: "charlie@example.com",
    amount: 2000,
    gstAmount: 360,
    totalAmount: 2360,
    status: "failed",
    createdAt: new Date("2025-12-04T11:20:00"),
    failureReason: "Insufficient balance in account",
  },
  {
    id: "pgt_005",
    paymentId: "pay_razorpay_PEND001",
    gateway: "razorpay",
    userId: "user_004",
    userName: "Diana Prince",
    userEmail: "diana@example.com",
    amount: 15000,
    gstAmount: 2700,
    totalAmount: 17700,
    status: "pending",
    createdAt: new Date("2025-12-05T16:45:00"),
  },
  {
    id: "pgt_006",
    paymentId: "pay_instamojo_SUCCESS02",
    gateway: "instamojo",
    userId: "reseller_002",
    userName: "Premium Events Ltd",
    userEmail: "info@premiumevents.com",
    amount: 75000,
    gstAmount: 13500,
    totalAmount: 88500,
    status: "success",
    walletTransactionId: "txn_wallet_004",
    createdAt: new Date("2025-12-06T13:00:00"),
    paidAt: new Date("2025-12-06T13:00:25"),
  },
  {
    id: "pgt_007",
    paymentId: "pay_cashfree_SUCCESS03",
    gateway: "cashfree",
    userId: "user_005",
    userName: "Eve Miller",
    userEmail: "eve@example.com",
    amount: 3000,
    gstAmount: 540,
    totalAmount: 3540,
    status: "success",
    walletTransactionId: "txn_wallet_005",
    createdAt: new Date("2025-12-07T08:30:00"),
    paidAt: new Date("2025-12-07T08:30:18"),
  },
]

export const mockUnmatchedPayments: UnmatchedPayment[] = [
  {
    id: "unm_001",
    paymentId: "pay_razorpay_UNMATCHED01",
    gateway: "razorpay",
    userId: "user_006",
    userName: "Frank Castle",
    userEmail: "frank@example.com",
    amount: 5000,
    status: "success",
    issue: "Payment successful but wallet transaction not found",
    reason: "Database connection timeout during wallet credit operation",
    detectedAt: new Date("2025-12-06T10:00:00"),
    resolved: false,
  },
  {
    id: "unm_002",
    paymentId: "pay_instamojo_UNMATCHED02",
    gateway: "instamojo",
    userId: "reseller_003",
    userName: "Stream Masters Inc",
    userEmail: "admin@streammasters.com",
    amount: 25000,
    status: "captured",
    issue: "Payment captured but wallet not credited",
    reason: "Server restart occurred after payment capture but before wallet update",
    detectedAt: new Date("2025-12-07T15:30:00"),
    resolved: false,
  },
  {
    id: "unm_003",
    paymentId: "pay_cashfree_UNMATCHED03",
    gateway: "cashfree",
    userId: "user_007",
    userName: "Grace Hopper",
    userEmail: "grace@example.com",
    amount: 8000,
    status: "success",
    issue: "Webhook not received, manual verification needed",
    reason: "Payment gateway webhook delivery failed due to network error",
    detectedAt: new Date("2025-12-08T09:45:00"),
    resolved: false,
  },
]

// ADDED FROM UPDATES:
// Mock GST Configurations
export const mockGSTConfigurations: GSTConfiguration[] = [
  {
    id: "gst-admin-1",
    entityId: "admin-1",
    entityType: "admin",
    gstEnabled: true,
    gstPercentage: 18,
    gstNumber: "27AABCU9603R1ZX",
    panNumber: "AABCU9603R",
    businessName: "StreamMattic Platform Pvt Ltd",
    businessAddress: "123 Business Park, Andheri East",
    city: "Mumbai",
    state: "Maharashtra",
    pincode: "400001",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date(),
  },
  {
    id: "gst-reseller-1",
    entityId: "reseller-1",
    entityType: "reseller",
    gstEnabled: true,
    gstPercentage: 18,
    gstNumber: "29AABCL1234M1Z5",
    panNumber: "AABCL1234M",
    businessName: "LiveStream Pro Media Services",
    businessAddress: "45 Tech Hub, Koramangala",
    city: "Bangalore",
    state: "Karnataka",
    pincode: "560034",
    createdAt: new Date("2024-02-15"),
    updatedAt: new Date(),
  },
  {
    id: "gst-reseller-2",
    entityId: "reseller-2",
    entityType: "reseller",
    gstEnabled: false,
    gstPercentage: 18,
    businessName: "StreamHub Media",
    businessAddress: "78 Digital Avenue",
    city: "Pune",
    state: "Maharashtra",
    pincode: "411001",
    createdAt: new Date("2024-03-01"),
    updatedAt: new Date(),
  },
  {
    id: "gst-user-1",
    entityId: "user-1",
    entityType: "user",
    gstEnabled: false,
    gstPercentage: 18,
    businessName: "Alice Johnson",
    businessAddress: "Personal Address",
    city: "Mumbai",
    state: "Maharashtra",
    pincode: "400001",
    createdAt: new Date("2024-06-01"),
    updatedAt: new Date(),
  },
]

export function getGSTConfig(entityId: string, entityType: string): GSTConfiguration | null {
  return (
    mockGSTConfigurations.find((config) => config.entityId === entityId && config.entityType === entityType) || null
  )
}
