import { TEMPLATE_DEFAULT_HERO_BACKDROP } from "./template-default-media"
import type { EventTemplate } from "./types"

export const EVENT_TEMPLATES: EventTemplate[] = [
  {
    id: "tpl-default",
    name: "Default",
    thumbnail: TEMPLATE_DEFAULT_HERO_BACKDROP["tpl-default"] ?? "",
    category: "General",
    isActive: true,
    sortOrder: 1,
  },
  {
    id: "tpl-wedding",
    name: "Wedding",
    thumbnail: TEMPLATE_DEFAULT_HERO_BACKDROP["tpl-wedding"] ?? "",
    category: "Wedding",
    isActive: true,
    sortOrder: 2,
  },
  {
    id: "tpl-wedding-garden",
    name: "Ethereal Garden Wedding",
    thumbnail: TEMPLATE_DEFAULT_HERO_BACKDROP["tpl-wedding-garden"] ?? "",
    category: "Wedding",
    isActive: true,
    sortOrder: 2.5,
  },
  {
    id: "tpl-wedding-midnight",
    name: "Midnight Elegance Wedding",
    thumbnail: TEMPLATE_DEFAULT_HERO_BACKDROP["tpl-wedding-midnight"] ?? "",
    category: "Wedding",
    isActive: true,
    sortOrder: 2.55,
  },
  {
    id: "tpl-wedding-coastal",
    name: "Coastal Breeze Wedding",
    thumbnail: TEMPLATE_DEFAULT_HERO_BACKDROP["tpl-wedding-coastal"] ?? "",
    category: "Wedding",
    isActive: true,
    sortOrder: 2.56,
  },
  {
    id: "tpl-wedding-celestial",
    name: "Celestial Dreams Wedding",
    thumbnail: TEMPLATE_DEFAULT_HERO_BACKDROP["tpl-wedding-celestial"] ?? "",
    category: "Wedding",
    isActive: true,
    sortOrder: 2.57,
  },
  {
    id: "tpl-wedding-traditional-hindu",
    name: "Shubh Vivah",
    thumbnail: TEMPLATE_DEFAULT_HERO_BACKDROP["tpl-wedding-traditional-hindu"] ?? "",
    category: "Wedding",
    isActive: true,
    sortOrder: 2.58,
  },
  {
    id: "tpl-wedding-the-heart",
    name: "The Heart Wedding",
    thumbnail: TEMPLATE_DEFAULT_HERO_BACKDROP["tpl-wedding-the-heart"] ?? "",
    category: "Wedding",
    isActive: true,
    sortOrder: 2.59,
  },
  {
    id: "tpl-wedding-royal-circle",
    name: "Royal Circle Wedding",
    thumbnail: TEMPLATE_DEFAULT_HERO_BACKDROP["tpl-wedding-royal-circle"] ?? "",
    category: "Wedding",
    isActive: true,
    sortOrder: 2.5905,
  },
  {
    id: "tpl-wedding-papercut",
    name: "Papercut Wedding",
    thumbnail: TEMPLATE_DEFAULT_HERO_BACKDROP["tpl-wedding-papercut"] ?? "",
    category: "Wedding",
    isActive: true,
    sortOrder: 2.5906,
  },
  {
    id: "tpl-corporate-tech-forward",
    name: "Tech Forward Summit",
    thumbnail: TEMPLATE_DEFAULT_HERO_BACKDROP["tpl-corporate-tech-forward"] ?? "",
    category: "Corporate",
    isActive: true,
    sortOrder: 22.7,
  },
  {
    id: "tpl-corporate",
    name: "Corporate Event",
    thumbnail: TEMPLATE_DEFAULT_HERO_BACKDROP["tpl-corporate"] ?? "",
    category: "Corporate",
    isActive: true,
    sortOrder: 22.72,
  },
  {
    id: "tpl-concert",
    name: "Music Concert",
    thumbnail: TEMPLATE_DEFAULT_HERO_BACKDROP["tpl-concert"] ?? "",
    category: "Entertainment",
    isActive: true,
    sortOrder: 4,
  },
  {
    id: "tpl-christian",
    name: "Christian Wedding",
    thumbnail: TEMPLATE_DEFAULT_HERO_BACKDROP["tpl-christian"] ?? "",
    category: "Wedding",
    extraCategories: ["Religious"],
    isActive: true,
    sortOrder: 2.59,
  },
  {
    id: "tpl-christian-wedding-rose",
    name: "Christian Wedding (Rose & Faith)",
    thumbnail: TEMPLATE_DEFAULT_HERO_BACKDROP["tpl-christian-wedding-rose"] ?? "",
    category: "Wedding",
    extraCategories: ["Religious"],
    isActive: true,
    sortOrder: 2.591,
  },
  {
    id: "tpl-muslim-wedding-nikah",
    name: "Muslim Wedding (Nikah Live)",
    thumbnail: TEMPLATE_DEFAULT_HERO_BACKDROP["tpl-muslim-wedding-nikah"] ?? "",
    category: "Wedding",
    extraCategories: ["Religious"],
    isActive: true,
    sortOrder: 2.595,
  },
  {
    id: "tpl-muslim",
    name: "Muslim Wedding",
    thumbnail: TEMPLATE_DEFAULT_HERO_BACKDROP["tpl-muslim"] ?? "",
    category: "Wedding",
    extraCategories: ["Religious"],
    isActive: true,
    sortOrder: 2.6,
  },
  {
    id: "tpl-hindu",
    name: "Hindu Ceremony",
    thumbnail: TEMPLATE_DEFAULT_HERO_BACKDROP["tpl-hindu"] ?? "",
    category: "Religious",
    isActive: true,
    sortOrder: 7,
  },
  {
    id: "tpl-sports",
    name: "Sports Event",
    thumbnail: TEMPLATE_DEFAULT_HERO_BACKDROP["tpl-sports"] ?? "",
    category: "Sports",
    isActive: true,
    sortOrder: 8,
  },
  {
    id: "tpl-political",
    name: "Political Event",
    thumbnail: TEMPLATE_DEFAULT_HERO_BACKDROP["tpl-political"] ?? "",
    category: "Political",
    isActive: true,
    sortOrder: 9,
  },
  {
    id: "tpl-school",
    name: "School Event",
    thumbnail: TEMPLATE_DEFAULT_HERO_BACKDROP["tpl-school"] ?? "",
    category: "Education",
    isActive: true,
    sortOrder: 10,
  },
  {
    id: "tpl-funeral",
    name: "Memorial Service",
    thumbnail: TEMPLATE_DEFAULT_HERO_BACKDROP["tpl-funeral"] ?? "",
    category: "Memorial",
    isActive: true,
    sortOrder: 99,
  },
  {
    id: "tpl-indian-festival",
    name: "Indian Festival",
    thumbnail: TEMPLATE_DEFAULT_HERO_BACKDROP["tpl-indian-festival"] ?? "",
    category: "General",
    isActive: true,
    sortOrder: 11,
  },
  {
    id: "tpl-gaming",
    name: "Gaming Event",
    thumbnail: TEMPLATE_DEFAULT_HERO_BACKDROP["tpl-gaming"] ?? "",
    category: "Entertainment",
    isActive: true,
    sortOrder: 12,
  },
  {
    id: "tpl-podcast",
    name: "Podcast",
    thumbnail: TEMPLATE_DEFAULT_HERO_BACKDROP["tpl-podcast"] ?? "",
    category: "Entertainment",
    isActive: true,
    sortOrder: 13,
  },
  {
    id: "tpl-movie-premiere",
    name: "Movie Premiere",
    thumbnail: TEMPLATE_DEFAULT_HERO_BACKDROP["tpl-movie-premiere"] ?? "",
    category: "Entertainment",
    isActive: true,
    sortOrder: 14,
  },
  {
    id: "tpl-award-ceremony",
    name: "Award Ceremony",
    thumbnail: TEMPLATE_DEFAULT_HERO_BACKDROP["tpl-award-ceremony"] ?? "",
    category: "Entertainment",
    isActive: true,
    sortOrder: 15,
  },
  {
    id: "tpl-comedy-show",
    name: "Comedy Show",
    thumbnail: TEMPLATE_DEFAULT_HERO_BACKDROP["tpl-comedy-show"] ?? "",
    category: "Entertainment",
    isActive: true,
    sortOrder: 16,
  },
  {
    id: "tpl-product-launch",
    name: "Product Launch",
    thumbnail: TEMPLATE_DEFAULT_HERO_BACKDROP["tpl-product-launch"] ?? "",
    category: "Business",
    isActive: true,
    sortOrder: 17,
  },
  {
    id: "tpl-webinar",
    name: "Webinar",
    thumbnail: TEMPLATE_DEFAULT_HERO_BACKDROP["tpl-webinar"] ?? "",
    category: "Business",
    isActive: true,
    sortOrder: 18,
  },
  {
    id: "tpl-auction",
    name: "Auction",
    thumbnail: TEMPLATE_DEFAULT_HERO_BACKDROP["tpl-auction"] ?? "",
    category: "Business",
    isActive: true,
    sortOrder: 19,
  },
  {
    id: "tpl-real-estate",
    name: "Real Estate",
    thumbnail: TEMPLATE_DEFAULT_HERO_BACKDROP["tpl-real-estate"] ?? "",
    category: "Business",
    isActive: true,
    sortOrder: 20,
  },
  {
    id: "tpl-baby-shower",
    name: "Baby Shower",
    thumbnail: TEMPLATE_DEFAULT_HERO_BACKDROP["tpl-baby-shower"] ?? "",
    category: "Social",
    isActive: true,
    sortOrder: 21,
  },
  {
    id: "tpl-birthday-party",
    name: "Birthday Party Bash",
    thumbnail: TEMPLATE_DEFAULT_HERO_BACKDROP["tpl-birthday-party"] ?? "",
    category: "Social",
    isActive: true,
    sortOrder: 22,
  },
  {
    id: "tpl-graduation",
    name: "Graduation",
    thumbnail: TEMPLATE_DEFAULT_HERO_BACKDROP["tpl-graduation"] ?? "",
    category: "Social",
    isActive: true,
    sortOrder: 23,
  },
  {
    id: "tpl-engagement",
    name: "Engagement",
    thumbnail: TEMPLATE_DEFAULT_HERO_BACKDROP["tpl-engagement"] ?? "",
    category: "Social",
    isActive: true,
    sortOrder: 24,
  },
  {
    id: "tpl-anniversary",
    name: "Anniversary",
    thumbnail: TEMPLATE_DEFAULT_HERO_BACKDROP["tpl-anniversary"] ?? "",
    category: "Social",
    isActive: true,
    sortOrder: 25,
  },
  {
    id: "tpl-reunion",
    name: "Reunion",
    thumbnail: TEMPLATE_DEFAULT_HERO_BACKDROP["tpl-reunion"] ?? "",
    category: "Social",
    isActive: true,
    sortOrder: 26,
  },
  {
    id: "tpl-chinese-festival",
    name: "Chinese Festival",
    thumbnail: TEMPLATE_DEFAULT_HERO_BACKDROP["tpl-chinese-festival"] ?? "",
    category: "Holiday",
    isActive: true,
    sortOrder: 27,
  },
  {
    id: "tpl-christmas",
    name: "Christmas",
    thumbnail: TEMPLATE_DEFAULT_HERO_BACKDROP["tpl-christmas"] ?? "",
    category: "Holiday",
    isActive: true,
    sortOrder: 28,
  },
  {
    id: "tpl-eid",
    name: "Eid Celebration",
    thumbnail: TEMPLATE_DEFAULT_HERO_BACKDROP["tpl-eid"] ?? "",
    category: "Holiday",
    isActive: true,
    sortOrder: 29,
  },
  {
    id: "tpl-thanksgiving",
    name: "Thanksgiving",
    thumbnail: TEMPLATE_DEFAULT_HERO_BACKDROP["tpl-thanksgiving"] ?? "",
    category: "Holiday",
    isActive: true,
    sortOrder: 30,
  },
  {
    id: "tpl-halloween",
    name: "Halloween",
    thumbnail: TEMPLATE_DEFAULT_HERO_BACKDROP["tpl-halloween"] ?? "",
    category: "Holiday",
    isActive: true,
    sortOrder: 31,
  },
  {
    id: "tpl-fitness",
    name: "Fitness",
    thumbnail: TEMPLATE_DEFAULT_HERO_BACKDROP["tpl-fitness"] ?? "",
    category: "Health",
    isActive: true,
    sortOrder: 32,
  },
  {
    id: "tpl-charity",
    name: "Charity",
    thumbnail: TEMPLATE_DEFAULT_HERO_BACKDROP["tpl-charity"] ?? "",
    category: "Social",
    isActive: true,
    sortOrder: 34,
  },
]

/**
 * Hidden from the Add/Edit Event template grid (streamer + studio).
 * Preview routes and legacy events may still reference these ids.
 */
export const EVENT_FORM_HIDDEN_TEMPLATE_IDS: ReadonlySet<string> = new Set([
  "tpl-corporate",
  "tpl-concert",
  "tpl-christian",
  "tpl-muslim",
  "tpl-hindu",
  "tpl-sports",
  "tpl-political",
  "tpl-school",
  "tpl-indian-festival",
  "tpl-gaming",
  "tpl-podcast",
  "tpl-movie-premiere",
  "tpl-award-ceremony",
  "tpl-comedy-show",
  "tpl-product-launch",
  "tpl-webinar",
  "tpl-auction",
  "tpl-real-estate",
  "tpl-baby-shower",
  "tpl-graduation",
  "tpl-engagement",
  "tpl-anniversary",
  "tpl-reunion",
  "tpl-chinese-festival",
  "tpl-christmas",
  "tpl-eid",
  "tpl-thanksgiving",
  "tpl-halloween",
  "tpl-fitness",
  "tpl-charity",
])

/** Subset shown in the event form template picker */
export const SELECTABLE_EVENT_TEMPLATES: EventTemplate[] = EVENT_TEMPLATES.filter(
  (t) => !EVENT_FORM_HIDDEN_TEMPLATE_IDS.has(t.id),
)

